### ISSUE TITLE
Test that CANToolz CAN232 works with arduino-canhacker library

### ISSUE THREAD

**Issue by DePierre** [CANToolz/CANToolz#18]
In addition to https://github.com/latonita/arduino-canbus-monitor (the library used to test CAN232), another popular one seems to be https://github.com/autowp/arduino-canhacker.

It would be nice to test it as well and make sure that it works with CANToolz's CAN232 module.

**Comment by all4diag** [comment]
Hi, im newbie tpo CANtoolz and just test it with arduino leonardo, the can232 is found with serial b0101 and when switching to localhost:44444 i receive bllank page with npo valid path.
Any help is welcome.

**Comment by DePierre** [comment]
@all4diag I would suggest coming to our telegram group to chat up and see what's your problem.

A few questions we would need you to answer in order to be able to help you:
- Are you using the latest release? (https://github.com/CANToolz/CANToolz/releases/tag/v3.7.0)
- Are you using Windows/Linux/Mac?
- Did you run `python setup.py install`?
- Was the installation successful? Were there any error messages?
- What command are you running to start CANToolz?
- What happens if you run the CLI interface (i.e. `cantoolz -g c`)?

**Comment by all4diag** [comment]
@DePierre
  im using last release 3.7.0 with python 3.4 under windows xp
  installed all dependencie correctly - pyserial numpy bitstring mido .. -
  installed setup.py from cmd line in CANToolz repertory installation was successful.
  
  i use this commande to run CANToolz:  $ python cantoolz.py -g w -c       examples/can_arduino.py
  iv changed com port to in can_arduino.py to my leonardo port 

  in the CLI after 10 attempt  can232:  sneding b\r receive error flushing the queue then   more 5 attempt
  hw_can232 found c232 version b 0101

try to launch cantoolz.py -g c i recieve error no such gui

**Comment by all4diag** [comment]
yes working tested with arduino leonardo and Niren can board .

**Comment by DePierre** [comment]
Excellent! Thank you @all4diag for testing the support :)
