### ISSUE TITLE
Create Wiki page for Windows/Mac installation

### ISSUE THREAD

**Issue by DePierre** [CANToolz/CANToolz#19]
Currently, the README of the repo describes how to install CANToolz with Linux. It would be nice to have a wiki page that also describes the Windows installation (and Mac, although it works the same as Linux but better write it down IMO).

That installation Wiki page would describe how to install CANToolz on all three systems.

**Comment by all4diag** [comment]
here my experience under windows (installation steps and starting CANtoolz)

[how i get it working.txt](https://github.com/CANToolz/CANToolz/files/1516212/how.i.get.it.working.txt)

thanks to @DePierre  who help me toget it working.

**Comment by DePierre** [comment]
Installation steps updated for Windows and Mac in https://github.com/CANToolz/CANToolz/wiki/Installation-and-basic-usage#windows
